### ISSUE TITLE
link to github is invalid in npm package

### ISSUE THREAD

**Issue by jberube** [christianrondeau/grunt-unfold#3]
On https://www.npmjs.com/package/grunt-unfold , the link to github is github.com:christianrondeau/grunt-unfold.git , it should be https://github.com/christianrondeau/grunt-unfold.git

see https://docs.npmjs.com/files/package.json#repository

**Comment by christianrondeau** [comment]
The value was correct, but indeed npmjs.com did not show it correctly. Looking at other packages, it seems simply providing `repository: "christianrondeau/grunt-unfold"` is sufficient... and the link now works :smile: - I used the opportunity to update dependencies.
